## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Handel House of America"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/handelhouse-marker.jpeg"
  favicon = false

[Params.social]
  github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/caressofsteel_"
  email = "caressofsteel@protonmail.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"